# Generated by Django 3.0.5 on 2021-04-02 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0004_auto_20210403_0054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='url',
        ),
    ]
