# Generated by Django 3.0.5 on 2021-04-03 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0005_remove_link_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='url',
            field=models.URLField(default=' '),
            preserve_default=False,
        ),
    ]
