# Generated by Django 3.0.5 on 2021-04-03 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0008_link_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='url',
        ),
    ]
